# Generated by Django 4.0.6 on 2022-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='name',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='type',
            field=models.CharField(choices=[('word', 'word'), ('phrase', 'phrase')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
