# Generated by Django 4.0.6 on 2022-07-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
