# Generated by Django 4.0.6 on 2022-11-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sentence_word_alter_sentence_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='word',
        ),
        migrations.AddField(
            model_name='sentence',
            name='Vocabulary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sentence', to='core.vocabulary'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.TextField()),
                ('Vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='core.vocabulary')),
            ],
        ),
    ]
