# Generated by Django 4.0.6 on 2022-11-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sentence_created_remove_sentence_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='Vocabulary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='core.vocabulary'),
        ),
    ]
