# Generated by Django 4.0.6 on 2022-11-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_word_vocabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='id',
        ),
        migrations.AlterField(
            model_name='word',
            name='Vocabulary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='word', serialize=False, to='core.vocabulary'),
        ),
    ]
