# Generated by Django 4.0.6 on 2022-11-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_vocabulary_sentence_vocabulary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='core.vocabulary'),
        ),
    ]
